<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <!--NOTE: We reference the RocksDbSharp.Lite project directly but use the RocksDB package to copy the required runtime files.
             If the version of RocksDB is updated in the package, don't forget to update the version below.
    -->
    <ProjectReference Include="..\..\lite\RocksDbSharp.Lite.csproj" />
    <PackageReference Include="RocksDB" Version="10.4.2.64152" ExcludeAssets="compile;runtime" PrivateAssets="all" GeneratePathProperty="true" />
    <None Include="$(NuGetPackageRoot)RocksDB\10.4.2.64152\runtimes\**\*" CopyToOutputDirectory="PreserveNewest" Visible="false" TargetPath="runtimes\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
