trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

container: curiosityai/rocksdb-build-linux:latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ROCKSDBVNUM=`cat rocksdbversion`
      echo "##vso[task.setvariable variable=ROCKSDBVERSION]${ROCKSDBVNUM}"
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/build-native/build-rocksdb.sh'
    workingDirectory: '$(Build.SourcesDirectory)/build-native/'

- task: CmdLine@2
  inputs:
    script: 'ls $(Build.SourcesDirectory) -hR'
  
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Curiosity GmbH Azure'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f $(Build.SourcesDirectory)/build-native/runtimes/linux-x64/native/librocksdb.so --account-name curiosityreleases  -c rocksdb  -n librocksdb-v$(ROCKSDBVERSION).so  --overwrite true'
