trigger:
- master

variables:
  vsdir: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\'

pool:
  vmImage: 'windows-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ROCKSDBVNUM=`cat rocksdbversion`
      echo "##vso[task.setvariable variable=ROCKSDBVERSION]${ROCKSDBVNUM}"
    workingDirectory: '$(Build.SourcesDirectory)'




- task: CmdLine@2
  inputs:
    script: |
      echo here1
      call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\Tools\\vsdevcmd" -arch=x64 && bash build-rocksdb.sh
      echo here2
    workingDirectory: '$(Build.SourcesDirectory)/build-native/'

- task: CmdLine@2
  inputs:
    script: 'ls $(Build.SourcesDirectory) -hR'
  
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Curiosity GmbH Azure'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f $(Build.SourcesDirectory)/build-native/runtimes/win-x64/native/rocksdb.dll --account-name curiosityreleases  -c rocksdb  -n rocksdb-v$(ROCKSDBVERSION).dll  --overwrite true'
