trigger:
- master

pool:
  vmImage: 'windows-latest'

strategy:
  matrix:
    x64:
      windowsTargetArch: 'x64'
      windowsRuntimeId: 'win-x64'
      vsDevCmdArch: 'amd64'
    arm64:
      windowsTargetArch: 'arm64'
      windowsRuntimeId: 'win-arm64'
      vsDevCmdArch: 'arm64'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ROCKSDBVNUM=`cat rocksdbversion`
      echo "##vso[task.setvariable variable=ROCKSDBVERSION]${ROCKSDBVNUM}"
    workingDirectory: '$(Build.SourcesDirectory)'




- task: CmdLine@2
  inputs:
    script: |
      echo here1
      call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\Tools\\vsdevcmd" -host_arch=amd64 -arch=$(vsDevCmdArch) && set WINDOWS_TARGET_ARCH=$(windowsTargetArch) && bash build-rocksdb.sh
      echo here2
    workingDirectory: '$(Build.SourcesDirectory)/build-native/'

- task: CmdLine@2
  inputs:
    script: 'ls $(Build.SourcesDirectory) -hR'
  
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Curiosity GmbH Azure'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f $(Build.SourcesDirectory)/build-native/runtimes/$(windowsRuntimeId)/native/rocksdb.dll --account-name curiosityreleases  -c rocksdb  -n rocksdb-v$(ROCKSDBVERSION)-$(windowsTargetArch).dll  --overwrite true'
