trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ROCKSDBVNUM=`cat rocksdbversion`
      echo "##vso[task.setvariable variable=ROCKSDBVERSION]${ROCKSDBVNUM}.$(build.buildId)"
      echo "##vso[task.setvariable variable=ROCKSDBVERSIONBASE]${ROCKSDBVNUM}"
    workingDirectory: '$(Build.SourcesDirectory)'

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET 9.0 sdk'
  inputs:
    packageType: sdk
    version: 9.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir /tmp/rocksdbjar
      pushd /tmp/rocksdbjar
      wget https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/$(ROCKSDBVERSIONBASE)/rocksdbjni-$(ROCKSDBVERSIONBASE)-linux64.jar
      unzip rocksdbjni-$(ROCKSDBVERSIONBASE)-linux64.jar
      ls -hR
      mv librocksdbjni-linux-aarch64.so $(Build.SourcesDirectory)/csharp/runtimes/linux-arm64/native/librocksdb.so
      mv librocksdbjni-linux-aarch64.so $(Build.SourcesDirectory)/csharp/runtimes/linux-arm64/native/librocksdb-musl.so
      mv librocksdbjni-linux64.so $(Build.SourcesDirectory)/csharp/runtimes/linux-x64/native/librocksdb.so
      mv librocksdbjni-linux64-musl.so $(Build.SourcesDirectory)/csharp/runtimes/linux-x64/native/librocksdb-musl.so
      ls $(Build.SourcesDirectory) -hR
      popd

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir /tmp/rocksdbjar
      pushd /tmp/rocksdbjar
      wget https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/$(ROCKSDBVERSIONBASE)/rocksdbjni-$(ROCKSDBVERSIONBASE)-osx.jar
      unzip rocksdbjni-$(ROCKSDBVERSIONBASE)-osx.jar
      ls -hR
      mv librocksdbjni-osx-arm64.jnilib $(Build.SourcesDirectory)/csharp/runtimes/osx-arm64/native/librocksdb.dylib
      mv librocksdbjni-osx-x86_64.jnilib $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/librocksdb.dylib
      ls $(Build.SourcesDirectory) -hR
      popd

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: '$(Build.SourcesDirectory)/build-codegen/CSharpGen.csproj'
    workingDirectory: '$(Build.SourcesDirectory)/build-codegen/'
    
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Curiosity GmbH Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/win-x64/native/rocksdb.dll --account-name curiosityreleases  -c rocksdb  -n rocksdb-v$(ROCKSDBVERSIONBASE).dll'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Curiosity GmbH Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/linux-x64/native/librocksdb-jemalloc.so --account-name curiosityreleases  -c rocksdb  -n librocksdb-v$(ROCKSDBVERSIONBASE).so'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Curiosity GmbH Azure'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/librocksdb.dylib --account-name curiosityreleases  -c rocksdb  -n librocksdb-v$(ROCKSDBVERSIONBASE).dylib'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Curiosity GmbH Azure'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/liblz4.dylib --account-name curiosityreleases  -c rocksdb  -n liblz4-v$(ROCKSDBVERSIONBASE).dylib'

# #- task: AzureCLI@2
# #  inputs:
# #    azureSubscription: 'Curiosity GmbH Azure'
# #    scriptType: 'bash'
# #    scriptLocation: 'inlineScript'
# #    inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/libbz.dylib --account-name curiosityreleases  -c rocksdb  -n libbz-v$(ROCKSDBVERSIONBASE).dylib'


# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Curiosity GmbH Azure'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/libsnappy.dylib --account-name curiosityreleases  -c rocksdb  -n libsnappy-v$(ROCKSDBVERSIONBASE).dylib'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Curiosity GmbH Azure'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/libz.dylib --account-name curiosityreleases  -c rocksdb  -n libz-v$(ROCKSDBVERSIONBASE).dylib'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Curiosity GmbH Azure'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az storage blob download -f $(Build.SourcesDirectory)/csharp/runtimes/osx-x64/native/libzstd.dylib --account-name curiosityreleases  -c rocksdb  -n libzstd-v$(ROCKSDBVERSIONBASE).dylib'



- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/csharp/RocksDbSharp.csproj'
    workingDirectory: '$(Build.SourcesDirectory)/csharp/'
    arguments: '-c Release /p:Version=$(ROCKSDBVERSION) /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: CmdLine@2
  inputs:
    script: 'ls $(Build.SourcesDirectory) -hR'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: '$(Build.SourcesDirectory)/csharp/RocksDbSharp.csproj'
    configuration: 'Release'
    versioningScheme: 'off'

- task: CmdLine@2
  inputs:
    script: 'ls $(Build.SourcesDirectory) -hR'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'
