
name: Build Linux
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute 
        run: |
          cat rocksdbversion
          sh ${{ github.workspace }}/build-native/build-rocksdb.sh
        
        working-directory: ${{ github.workspace }}/build-native/
