
name: .NET Core Desktop
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/vsdevenv-shell@v1
    
      - name: Checkout
        with:
          fetch-depth: 0
      - name: Execute 
        shell: vsdevenv x64 bash {0}
        run: ${{ github.workspace }}/build-native/build-rocksdb.sh
