
name: Build Linux
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: curiosityai/rocksdb-build-linux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute 
        working-directory: ${{ github.workspace }}/build-native/
        run: |
          apt-get install libsnappy-dev -y
          bash ${{ github.workspace }}/build-native/build-rocksdb.sh
